### ISSUE TITLE
Host examples on vercel?

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs-pro-react#1]
Would it be possible to host the examples on Vercel?

**Comment by borislobanov92** [comment]
It would be possible but I'm not sure I see a lot of value in it. The examples are mainly useful for 2 reasons in my opinion: a) users will be able to look at the code to see how to integrate the hook and b) they will be able to serve them locally and tweak something to see how the changes affect results.
Hosting the demo would mainly showcase the use of the JS agent (however nothing about it is React specific) and the caching mechanism that will be only noticeable with the Network and Application tabs open in DevTools. Still I'm not sure that hosting examples will increase adoption of the React SDK.
But I'm keeping an open mind :)

**Comment by Valve** [comment]
Thanks, let's keep this open to invite more community votes.

**Comment by EmmanuelTheCoder** [comment]
I agree with @borislobanov92.  Perhaps, we could put it on CodeSandbox so that users can make changes and see how it affect results.
