### ISSUE TITLE
Installing fingerprintjs on next.js app router

### ISSUE THREAD

**Issue by elaser** [fingerprintjs/fingerprintjs-pro-react#140]
Hi there!

When looking at the tutorial for installing fingerprintjs on next, it looks like the example is for Next page router:

```
// pages/_app.tsx
import {
  FpjsProvider
} from '@fingerprintjs/fingerprintjs-pro-react'
import {AppProps} from 'next/app'

export default function MyApp({Component, pageProps}: AppProps) {
  return (
    <FpjsProvider
      loadOptions={{
        apiKey: "<api key>"
      }}
    >
      <Component {...pageProps} />
    </FpjsProvider>
  )
}
```

I was wondering how this can be done with the new app router?  Thank you!

I tried putting it in `app/layout.tsx`

```
<body className={inter.className}>
      <FpjsProvider
      loadOptions={{
        apiKey: "<api key>"
      }}>
      </FpjsProvider>
      {children}  
      </body>
```

and then calling it from a page:

```'use client'
import Image from "next/image";
import { useVisitorData } from '@fingerprintjs/fingerprintjs-pro-react'

export default function Home() {
  const {isLoading, error, data, getData} = useVisitorData(
    {extendedResult: true},
    {immediate: true}
  )

  return (
    <div>
      <button onClick={() => getData({ignoreCache: true})}>
        Reload data
      </button>
      <p>VisitorId: {isLoading ? 'Loading...' : data?.visitorId}</p>
      <p>Full visitor data:</p>
      <pre>{error ? error.message : JSON.stringify(data, null, 2)}</pre>
    </div>
  );
}
```

but I get "Failed to load the JS script of the agent".  

Thank you for looking at this!

**Comment by elaser** [comment]
oops, turns out it was related to #104 !

**Comment by JuroUhlar** [comment]
Just for future reference, this is covered in the documentation here: [Usage with Server-side Rendering Frameworks](https://dev.fingerprint.com/docs/usage-with-server-side-rendering-frameworks#the-app-directory).

**Comment by JuroUhlar** [comment]
@PunithDandluri 
"Failed to load the JS script of the agent" is usually related to ad blockers. Try running your app in a browser without ad blockers (default Chrome for example). 

You can use one of our proxy integrations to solve the issue completely: https://dev.fingerprint.com/docs/protecting-the-javascript-agent-from-adblockers
