### ISSUE TITLE
Finger id not same 

### ISSUE THREAD

**Issue by rohitt-gupta** [fingerprintjs/fingerprintjs-pro-react#152]
I am using windows and i tried the demo on same PC one in guest browser and one in normal chrome, both of the ID's are different.
check ss below
![image](https://github.com/fingerprintjs/fingerprintjs-pro-react/assets/81370462/7607f42a-af06-4eb7-aae0-5356b675a84e)

**Comment by JuroUhlar** [comment]
Hi @rohitt-gupta! Thanks for reporting, I have forwarded your visitor IDs to our research team for investigation. Some percentage of false negatives is expected if too many browser attributes change simultaneously. See our [documentation](https://dev.fingerprint.com/docs/understanding-our-995-accuracy) for more details on how we measure accuracy.
