### ISSUE TITLE
Improve code snippets for the `visitorId` in readme

### ISSUE THREAD

**Issue by ilfa** [fingerprintjs/fingerprintjs-pro-react#42]
We need to find a way to show the usage of `visitorId` in code snippets to make examples more useful.
Use this discussion to get more context: https://github.com/fingerprintjs/fingerprintjs-pro-react/pull/6#discussion_r822537060

**Comment by JuroUhlar** [comment]
In the meantime, we have polished our code snippets, and I think they are adequate now ->  Closing. 

@ilfa let me know if you prefer to address this further, we can reopen it.
