### ISSUE TITLE
Add useful example for the `getData` method

### ISSUE THREAD

**Issue by ilfa** [fingerprintjs/fingerprintjs-pro-react#43]
In the example below we show how to call the `getData` method but don't afford any useful scenarios of what we can do with that data.
We need to add a better scenario to the documentation.

```jsx
<form
  onSubmit={(e) => {
    e.preventDefault()
    getData().then((data) => {
      if (data) {
        // do something with the visitor data
        // for example, append visitor data to the form data to send to your server
        console.log(data)
      }
    })
  }}
>
```

**Comment by ilfa** [comment]
Nice idea! Could you add the link to the readme?

**Comment by JuroUhlar** [comment]
Done: https://github.com/fingerprintjs/fingerprintjs-pro-react/pull/145/commits/bc055bcaf826aeb6e76d81191d916e519df48bda
